-- Clean junk AI-generated review summaries from locations table.
-- These are placeholder texts generated by Gemini when no real Google reviews exist.

UPDATE locations
SET google_review_summary = NULL
WHERE google_review_summary IS NOT NULL
AND (
  -- Too short to be a real summary
  LENGTH(TRIM(google_review_summary)) < 10
  -- Vietnamese junk patterns
  OR google_review_summary ILIKE '%không được cung cấp%'
  OR google_review_summary ILIKE '%không có thông tin%'
  OR google_review_summary ILIKE '%chưa có thông tin%'
  OR google_review_summary ILIKE '%chưa có review%'
  OR google_review_summary ILIKE '%chưa có đánh giá%'
  OR google_review_summary ILIKE '%không có dữ liệu%'
  OR google_review_summary ILIKE '%không tìm thấy%'
  OR google_review_summary ILIKE '%thông tin tóm tắt review%không%'
  OR google_review_summary ILIKE '%thông tin cụ thể%không%'
  OR google_review_summary ILIKE '%dữ liệu google maps%'
  -- English junk patterns
  OR google_review_summary ILIKE '%no review%'
  OR google_review_summary ILIKE '%not available%'
  OR google_review_summary ILIKE '%not provided%'
  OR TRIM(google_review_summary) ILIKE 'n/a'
);

-- Also clean google_highlights that contain junk
UPDATE locations
SET google_highlights = NULL
WHERE google_highlights IS NOT NULL
AND (
  array_length(google_highlights, 1) = 1
  AND (
    google_highlights[1] ILIKE '%không có%'
    OR google_highlights[1] ILIKE '%không được cung cấp%'
    OR google_highlights[1] ILIKE '%chưa có%'
    OR LENGTH(TRIM(google_highlights[1])) < 3
  )
);
