// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wsysphytctpgbzoatuzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeXNwaHl0Y3RwZ2J6b2F0dXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTkwMTksImV4cCI6MjA2NjA5NTAxOX0.cE5GDPElTr2khJrlX669M5fTxgLF4eY0dmvxHIGpmfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);